In [1]:
# coding: utf-8


import numpy as np

In [2]:
a = np.array([1, 2, 3, 4], dtype=np.float)
print(a)  # 打印 a
print(a.dtype)  # 打印 a 的数据类型
print(a.shape)  # 打印 a 的尺寸

[1. 2. 3. 4.]
float64
(4,)


In [3]:
print(np.arange(10))  # arange 的用法

[0 1 2 3 4 5 6 7 8 9]


In [4]:
a = np.array([1, 2, 3, 4], dtype=np.float)
b = a.astype(np.int64)  # 类型转换
print(a.dtype)
print(b.dtype)
print(a)
print(b)

float64
int64
[1. 2. 3. 4.]
[1 2 3 4]


In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.dtype)
print(a.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
print(a + a)  # 对应位置 +

[[ 2  4  6]
 [ 8 10 12]]


In [8]:
print(a - a)  # 对应位置 -

[[0 0 0]
 [0 0 0]]


In [9]:
print(a * a)  # 对应位置 *

[[ 1  4  9]
 [16 25 36]]


In [10]:
print(a / a)  # 对应位置 /

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(a ** 2)  # 对应位置 **2

[[ 1  4  9]
 [16 25 36]]


In [12]:
print(np.nan)  # NaN 值
print(np.inf)  # 无穷大

nan
inf


In [13]:
a = np.array([1, 2, np.nan, np.inf, 3, 4])
print(np.isnan(a))  # 是 NaN 值返回 True
print(np.isinf(a))  # 是无穷大返回 True
print(np.isfinite(a))  # 不是无穷大或者 NaN 值返回 True

[False False  True False False False]
[False False False  True False False]
[ True  True False False  True  True]


In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [15]:
print(np.add(a, b))
print(a + b)
print(np.subtract(a, b))
print(a - b)
print(np.multiply(a, b))
print(a * b)
print(np.divide(a, b))
print(a / b)
print(np.power(a, b))
print(a ** b)

[5 7 9]
[5 7 9]
[-3 -3 -3]
[-3 -3 -3]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
[  1  32 729]
[  1  32 729]


In [16]:
a = np.array([1, 2, 3, 4, np.nan, np.inf, np.nan, np.inf, np.nan])
b = np.array([2, 1, 2, np.nan, np.nan, np.inf, np.inf, 3, 4])
print(a.shape)
print(b.shape)

(9,)
(9,)


In [17]:
print(np.maximum(a, b))  # 对应位置的较大值，有 NaN 返回 NaN
print(np.fmax(a, b))  # 对应位置的较大值，有 NaN 返回不为 NaN 的值，都为 NaN 返回 NaN

[ 2.  2.  3. nan nan inf nan inf nan]
[ 2.  2.  3.  4. nan inf inf inf  4.]


d:\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in maximum
  """Entry point for launching an IPython kernel.


In [18]:
a = np.array([1, 2, 3, 4, np.nan, np.inf, np.nan, np.inf, np.nan])
print(np.sum(a))
print(np.mean(a))

nan
nan


In [19]:
a = np.array([1, 2, 3])
print(np.sum(a))
print(np.mean(a))
print(np.std(a))  # 标准差
print(np.var(a))  # 方差
print(np.min(a))
print(np.max(a))
print(np.argmin(a))  # 最小值对应的下标
print(np.argmax(a))  # 最大值对应的下标
print(np.cumsum(a))  # 累加
print(np.cumprod(a))  # 累乘

6
2.0
0.816496580927726
0.6666666666666666
1
3
0
2
[1 3 6]
[1 2 6]
