In [1]:
# encoding: utf-8


import numpy as np

In [2]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

In [3]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
# 矩阵 + 数字
print(A + 10)

[[ 66.   10.   14.4  78. ]
 [ 11.2 114.   62.   18. ]
 [ 11.8 145.  109.   10.9]]


In [5]:
col_sum = A.sum(axis = 0)  # 求各列的和
print(col_sum)

[ 59.  239.  155.4  76.9]


In [6]:
# 矩阵 * 一个数字 / 一个数组
percentage = 100 * A / col_sum
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [7]:
# 列向量 + 数字
A = np.array([1, 2, 3, 4]).reshape(4, 1)
B = 100
print(A + B)

[[101]
 [102]
 [103]
 [104]]


In [8]:
# 行向量 + 数字
A = np.array([1, 2, 3, 4]).reshape(1, 4)
B = 100
print(A + B)

[[101 102 103 104]]


In [9]:
# 矩阵 + 行向量
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[100, 200, 300]])
print(A + B)

[[101 202 303]
 [104 205 306]]


In [10]:
# 矩阵 + 列向量
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[100], [200]])
print(A + B)

[[101 102 103]
 [204 205 206]]
