In [1]:
# encoding: utf-8


import numpy as np

In [2]:
# numpy.hstack 是在第 2 个轴上进行合并，1 维数组没有第 2 个轴，所以 1 维数组可以看成水平合并

A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
C = np.hstack((A, B))
print('A.shape:', A.shape)
print('B.shape:', B.shape)
print('C.shape:', C.shape)
print('A = ', A)
print('B = ', B)
print('C = ', C)

In [3]:
A = np.array([[1], [2], [3]])
B = np.array([[1], [2], [3]])
C = np.hstack((A, B))
print('A.shape:', A.shape)
print('B.shape:', B.shape)
print('C.shape:', C.shape)
print('A = \n', A)
print('B = \n', B)
print('C = \n', C)

A.shape: (3, 1)
B.shape: (3, 1)
C.shape: (3, 2)
A = 
 [[1]
 [2]
 [3]]
B = 
 [[1]
 [2]
 [3]]
C = 
 [[1 1]
 [2 2]
 [3 3]]
