In [1]:
# encoding: utf-8



"""
row vector and column vector
"""


import numpy as np

In [16]:
# a 的 shape 为 (5,)
# a 既不是行向量也不是列向量
# a 只是秩为 1 的数组 (array)
a = np.random.randn(5)
print('a:')
print(a)
print('a.shape:', a.shape) 
print('type of a:', type(a))

a:
[-0.38471485 -0.29125155  0.56250371  1.22245346 -1.5610128 ]
a.shape: (5,)
type of a: <class 'numpy.ndarray'>


In [14]:
# 定义一个列向量
a = np.random.randn(5, 1)
print('a:')
print(a)
print('a.shape:', a.shape) 
print('type of a:', type(a))

a:
[[ 0.11307553]
 [-0.24896048]
 [ 0.44495301]
 [ 1.16563686]
 [-1.46257002]]
a.shape: (5, 1)
type of a: <class 'numpy.ndarray'>


In [18]:
# 定义一个列向量
a = np.random.randn(5).reshape(5, 1)
print('a:')
print(a)
print('a.shape:', a.shape) 
print('type of a:', type(a))

a:
[[-0.11772766]
 [-1.05902739]
 [-1.03733339]
 [ 0.24032049]
 [ 0.92371136]]
a.shape: (5, 1)
type of a: <class 'numpy.ndarray'>


In [19]:
# 定义一个列向量
a = np.array([[1], [2], [3], [4], [5]])
print('a:')
print(a)
print('a.shape:', a.shape) 
print('type of a:', type(a))

a:
[[1]
 [2]
 [3]
 [4]
 [5]]
a.shape: (5, 1)
type of a: <class 'numpy.ndarray'>


In [20]:
# 定义一个行向量
a = np.random.randn(1, 5)
print('a:')
print(a)
print('a.shape:', a.shape) 
print('type of a:', type(a))

a:
[[ 1.85745799 -0.51736037 -1.31659813 -0.80142942  0.64124853]]
a.shape: (1, 5)
type of a: <class 'numpy.ndarray'>


In [21]:
# 定义一个行向量
a = np.random.randn(5).reshape(1, 5)
print('a:')
print(a)
print('a.shape:', a.shape) 
print('type of a:', type(a))

a:
[[ 0.31170805 -0.21119158 -0.80170553 -0.14191598  1.4992062 ]]
a.shape: (1, 5)
type of a: <class 'numpy.ndarray'>


In [22]:
# 定义一个行向量
a = np.array([[1, 2, 3, 4, 5]])
print('a:')
print(a)
print('a.shape:', a.shape) 
print('type of a:', type(a))

a:
[[1 2 3 4 5]]
a.shape: (1, 5)
type of a: <class 'numpy.ndarray'>


In [25]:
assert(a.shape == (1, 5))
print('success (1, 5)')

success (1, 5)


In [31]:
# # AssertionError
# assert(a.shape == (1, 3))
# print('success (1, 3)')